[version]
# version to update to
major = 0
minor = 2
patch = 1

[paths]
# Locations of repositories to update
#
# ------------------------------------------------------
# (1) Path to  repository "whitenoise-core-python"
#   - e.g. "/Users/username/github/repos/whitenoise-core-python"
# ------------------------------------------------------
#
#python = "/Users/michael/whitenoise/python"
python = "/Users/ramanprasad/Documents/github-rp/whitenoise-core-python"
#
# ------------------------------------------------------
# (2) Path to repository "whitenoise-core"
#   - e.g. "/Users/username/github/repos/whitenoise-core-python/whitenoise-core"
#   - Normally this is the submodule within whitenoise-core-python
# ------------------------------------------------------
#
#core = "/Users/michael/whitenoise/python/whitenoise-core"
core = "/Users/ramanprasad/Documents/github-rp/whitenoise-core-python/whitenoise-core"
#
# ------------------------------------------------------
# (3) Path to the repository "whitenoise-core-r"
#  ** Currently not in use **
# ------------------------------------------------------
#
#R = "/Users/michael/whitenoise/R"
